[features]
seeds = false
skip-lint = false

[programs.localnet]
idenclave = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
idenclave = "E26WsLNacfSvEJcKMZ1667XPoNn3mDpyCb523sgaf8yy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "idenclave-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
