[features]
seeds = false
skip-lint = false

[programs.localnet]
idenclave = "Gp1WFWsFF7t84LgrZRv5ALoZsDf7YjRDzrc5FxE3zVUH"

[programs.devnet]
idenclave = "Gp1WFWsFF7t84LgrZRv5ALoZsDf7YjRDzrc5FxE3zVUH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "idenclave-new-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
